splash = false
splash_offset = 20
splash_opacity = 0.8
ipc = true

wallpaper {
    monitor =
    path = /home/noonomyen/Wallpapers/yande.re 1253726 hagimiya_luna indie_virtual_youtuber wallpaper yoshino_ryou.png
    fit_mode = cover
    timeout = 30
}
