general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd = pkill hyprlock && hyprctl dispatch dpms on
    on_lock_cmd =
    on_unlock_cmd =
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on && brightnessctl --restore
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
    inhibit_sleep = 3
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
    on-resume =
    ignore_inhibit = false
}

listener {
    timeout = 700
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl --restore
    ignore_inhibit = false
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
    on-resume =
    ignore_inhibit = false
}
