exec-once = hyprctl dispatch submap global

source = hyprland/envs.conf

source = hyprland/general.conf
source = hyprland/decoration.conf
source = hyprland/animations.conf
source = hyprland/input.conf
source = hyprland/gestures.conf
source = hyprland/group.conf
source = hyprland/misc.conf
source = hyprland/binds.conf
source = hyprland/xwayland.conf
source = hyprland/windowrule.conf
source = hyprland/opengl.conf
source = hyprland/render.conf
source = hyprland/cursor.conf
source = hyprland/ecosystem.conf
source = hyprland/quirks.conf
source = hyprland/debug.conf
source = hyprland/dwindle.conf

# source = workspaces.conf
source = monitors.conf

source = hyprland/execs.conf
