source = ./MatugenColor.conf

general {
    hide_cursor = false
    ignore_empty_input = false
    immediate_render = false
    text_trim = true
    fractional_scaling = 0
    screencopy_mode = 0
    fail_timeout = 3000
}

auth {
    pam {
        enabled = true
        module = hyprlock
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = @PATH@
    color = $color_surface
    blur_passes = 3
    blur_size = 8
    noise = 0.01
    contrast = 0.9
    brightness = 0.8
    vibrancy = 0.2
    vibrancy_darkness = 0.1
    reload_time = -1
    reload_cmd =
    crossfade_time = -1.0
    zindex = -1
}

# --- Time ---
label {
    monitor =
    text = cmd[update:1000] date '+%H:%M:%S'
    text_align = center
    color = $color_primary
    font_size = 72
    font_family = NotoSansM Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
    shadow_color = rgb(0, 0, 0)
    shadow_boost = 0.5
}

# --- Date ---
label {
    monitor =
    text = cmd[update:1000] date '+%A, %d %B %Y'
    text_align = center
    color = $color_onSurface
    font_size = 16
    font_family = NotoSansM Nerd Font
    position = 0, 0
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
    shadow_color = rgb(0, 0, 0)
    shadow_boost = 0.5
}

# --- Input Field ---
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 0
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    dots_rounding = -1

    # Completely transparent background and border
    outer_color = rgba(0, 0, 0, 0.0)
    inner_color = rgba(0, 0, 0, 0.0)

    # Dots color
    font_color = $color_primary
    font_family = NotoSansM Nerd Font

    fade_on_empty = true
    fade_timeout = 2000
    placeholder_text = <i></i>
    hide_input = false

    # Validation states colors
    check_color = rgba(0, 0, 0, 0.0)
    fail_color = rgba(0, 0, 0, 0.0)
    fail_text = Failed $ATTEMPTS

    position = 0, -120
    halign = center
    valign = center
    zindex = 0

    shadow_passes = 0
}
