$color_primary = rgba(ffb0cfff)
$color_onPrimary = rgba(531d37ff)
$color_primaryContainer = rgba(6e334eff)
$color_onPrimaryContainer = rgba(ffd9e5ff)
$color_secondary = rgba(e1bdc9ff)
$color_onSecondary = rgba(412a33ff)
$color_surface = rgba(191114ff)
$color_onSurface = rgba(eedfe2ff)
$color_surfaceVariant = rgba(504348ff)
$color_onSurfaceVariant = rgba(d5c2c7ff)
$color_outline = rgba(9d8c91ff)
$color_error = rgba(ffb4abff)
$color_onError = rgba(690005ff)
$color_errorContainer = rgba(93000aff)
$color_onErrorContainer = rgba(ffdad6ff)
