monitorv2 {
  output = eDP-1
  mode = 1920x1080@144
  position = 2560x0
  scale = 1
  cm = srgb
}

monitorv2 {
  output = HDMI-A-1
  mode = 2560x1440@120
  position = 0x0
  scale = 1

  bitdepth = 10
  cm = hdr

  supports_wide_color = 1
  supports_hdr = 1

  sdr_min_luminance = 0.20
  sdr_max_luminance = 210
  max_luminance = 400

  sdrbrightness = 1.06
  sdrsaturation = 0.98
}
