animations {
    enabled = yes
    bezier = emphasizedDecel, 0.05, 0.7, 0.1, 1.0
    bezier = snappyOvershoot, 0.4, 1.4, 0.2, 1.0
    bezier = menu_decel, 0.1, 1, 0, 1
    bezier = menu_accel, 0.52, 0.03, 0.72, 0.08
    bezier = stall, 1, -0.1, 0.7, 0.85
    animation = windowsIn, 1, 4, emphasizedDecel, popin 95%
    animation = windowsOut, 1, 3, emphasizedDecel, popin 95%
    animation = windowsMove, 1, 4, emphasizedDecel, slide
    animation = layersIn, 1, 4, emphasizedDecel, popin 95%
    animation = layersOut, 1, 3, menu_decel, fade
    animation = fadeIn, 1, 4, menu_decel
    animation = fadeOut, 1, 3, menu_decel
    animation = fadeLayersIn, 1, 3, menu_decel
    animation = fadeLayersOut, 1, 3, stall
    animation = fadePopupsIn, 1, 3, menu_decel
    animation = fadePopupsOut, 1, 3, menu_decel
    animation = workspaces, 1, 6, emphasizedDecel, slide
    animation = specialWorkspace, 1, 6, snappyOvershoot, slidevert
    animation = border, 1, 5, menu_decel
    animation = zoomFactor, 1, 4, emphasizedDecel
}
