binds {
    pass_mouse_when_bound = false
    scroll_event_delay = 0
    workspace_back_and_forth = false
    hide_special_on_workspace_change = false
    allow_workspace_cycles = false
    workspace_center_on = 0
    focus_preferred_method = 0
    ignore_group_lock = false
    movefocus_cycles_fullscreen = false
    movefocus_cycles_groupfirst = false
    disable_keybind_grabbing = true
    window_direction_monitor_fallback = true
    allow_pin_fullscreen = false
    drag_threshold = 0
}

submap = global

# Submap
bindu = SUPER_ALT, 1, submap, global
bindu = SUPER_ALT, `, submap, reset

# Workspace
bindu = , mouse:275, workspace, r+1
bindu = , mouse:276, workspace, r-1
bindu = SUPER, mouse_up, workspace, r+1
bindu = SUPER, mouse_down, workspace, r-1
#bindu = Ctrl + SUPER, Right, workspace, r+1
#bindu = Ctrl + SUPER, Left, workspace, r-1
bindu = SUPER, Page_Up, workspace, +1
bindu = SUPER, Page_Down, workspace, -1
bindu = SUPER, F2, workspace, +1
bindu = SUPER, F1, workspace, -1

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9

# Special workspace
bind = SUPER, S, togglespecialworkspace
#bind = SUPER, Space

# Window controlling
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
bind = SUPER, Left, movefocus, l
bind = SUPER, Right, movefocus, r
bind = SUPER, Up, movefocus, u
bind = SUPER, Down, movefocus, d
bind = SUPER_SHIFT, Left, movewindow, l
bind = SUPER_SHIFT, Right, movewindow, r
bind = SUPER_SHIFT, Up, movewindow, u
bind = SUPER_SHIFT, Down, movewindow, d
bind = SUPER_ALT, F1, exec, hyprctl dispatch movetoworkspace -1
bind = SUPER_ALT, F2, exec, hyprctl dispatch movetoworkspace +1
bind = SUPER, Q, killactive
bind = SUPER_SHIFT, Q, forcekillactive
bind = SUPER_SHIFT_ALT, Q, exec, hyprctl kill
bind = SUPER_ALT, Space, togglefloating
bind = SUPER, F, fullscreen, 0

# Shell
bind = SUPER, m, exec, quickshell ipc call nne_shell toggleSysMon

# Application and utilities
bind = SUPER, V, exec, cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy
bind = SUPER, SUPER_L, exec, pkill -INT rofi || rofi -show drun
bind = SUPER, TAB, exec, pkill -INT rofi || rofi -show window
bind = SUPER, R, exec, pkill -INT rofi || rofi -show run
bind = SUPER_SHIFT, C, exec, killall -9 hyprpicker || hyprpicker --autocopy --lowercase-hex
bindu = SUPER_SHIFT, S, exec, killall -9 hyprpicker || grimblast --notify --freeze copysave area ~/Pictures/Screenshots/$(date +'%Y%m%d-%H%M%S').png
bind = SUPER, Print, exec, killall -9 hyprpicker || grimblast --notify --freeze copysave output ~/Pictures/Screenshots/$(date +'%Y%m%d-%H%M%S').png
bind = SUPER_SHIFT, Print, exec, killall -9 hyprpicker || grimblast --notify --freeze copysave screen ~/Pictures/Screenshots/$(date +'%Y%m%d-%H%M%S').png
bind = SUPER, Return, exec, kitty -1

# Functions
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.5
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindle = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bindle = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bind = , XF86ScreenSaver, exec, hyprlock
