$color_active_border = rgba(9d8c9177)
$color_inactive_border = rgba(50434855)
$color_nogroup_border = rgba(19111430)
$color_nogroup_border_active = rgba(191114C0)

$color_group_border_active = rgba(ffb0cf66)
$color_group_border_inactive = rgba(50434866)
$color_group_border_locked_active = rgba(ffb4ab66)
$color_group_border_locked_inactive = rgba(93000a66)

$color_group_text = rgba(eedfe2FF)
$color_group_text_inactive = rgba(eedfe2FF)
$color_group_text_locked_active = rgba(eedfe2FF)
$color_group_text_locked_inactive = rgba(eedfe2FF)

$color_groupbar_active = rgba(ffb0cf66)
$color_groupbar_inactive = rgba(50434866)
$color_groupbar_locked_active = rgba(ffb4ab66)
$color_groupbar_locked_inactive = rgba(93000a66)

$color_splash = rgba(eedfe2FF)
$color_background = rgba(191114FF)
$color_shadow = rgba(000000EE)
$color_shadow_inactive = rgba(000000EE)

$color_pin_border_active = rgba(ffb0cfAA)
$color_pin_border_inactive = rgba(ffb0cf77)
