# Path
env = PATH, $HOME/.local/override-bin:$HOME/.local/bin:$PATH

# Aquamarine
env = AQ_DRM_DEVICES, /dev/dri/by-path/card-igpu
env = AQ_FORCE_LINEAR_BLIT, 0
env = AQ_MGPU_NO_EXPLICIT, 0
env = AQ_NO_MODIFIERS, 0
env = AQ_NO_ATOMIC, 0

# Wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = WLR_NO_HARDWARE_CURSORS, 0

# Themes
env = QT_QPA_PLATFORM, wayland
env = QT_QPA_PLATFORMTHEME, qt6ct

env = XCURSOR_SIZE, 22
env = XCURSOR_THEME, Bibata-Modern-Classic
env = HYPRCURSOR_SIZE, 22
env = HYPRCURSOR_THEME, Bibata-Modern-Classic

# Applications
#env = QS_DISABLE_DMABUF, 1
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

# Libva (Hardware video acceleration)
env = LIBVA_DRIVER_NAME, nvidia
env = NVD_BACKEND, direct
