exec-once = systemctl --user start hyprpaper.service
exec-once = systemctl --user start hyprsunset.service
exec-once = systemctl --user start hypridle.service
exec-once = systemctl --user start quickshell.service
exec-once = systemctl --user start cliphist.service

exec-once = /home/noonomyen/.config/hypr/scripts/submap-switch.sh

