general {
    gaps_in = 1
    gaps_out = 4
    gaps_workspaces = 20
    float_gaps = 0

    border_size = 2
    col.inactive_border = 0x300477bf
    col.active_border = 0xc00455bf
    col.nogroup_border = 0x30000000
    col.nogroup_border_active = 0xc0000000

    layout = dwindle
    no_focus_fallback = true
    resize_on_border = false
    extend_border_grab_area = 0
    hover_icon_on_border = false
    allow_tearing = true
    resize_corner = 0
    modal_parent_blocking = false
    locale =

    snap {
        enabled = true
        window_gap = 5
        monitor_gap = 5
        border_overlap = true
        respect_gaps = true
    }
}
