# Shell
layerrule = match:namespace ^quickshell:.*, blur on
layerrule = match:namespace ^quickshell:.*, no_anim on
layerrule = match:namespace ^quickshell:.*, ignore_alpha 0

# Applications
windowrule = match:class kitty, opacity 0.9 0.9
windowrule = border_color $color_pin_border_active $color_pin_border_inactive, match:pin 1
