$color_active_border = rgba({{colors.outline.default.hex_stripped}}77)
$color_inactive_border = rgba({{colors.outline_variant.default.hex_stripped}}55)
$color_nogroup_border = rgba({{colors.background.default.hex_stripped}}30)
$color_nogroup_border_active = rgba({{colors.background.default.hex_stripped}}C0)

$color_group_border_active = rgba({{colors.primary.default.hex_stripped}}66)
$color_group_border_inactive = rgba({{colors.outline_variant.default.hex_stripped}}66)
$color_group_border_locked_active = rgba({{colors.error.default.hex_stripped}}66)
$color_group_border_locked_inactive = rgba({{colors.error_container.default.hex_stripped}}66)

$color_group_text = rgba({{colors.on_surface.default.hex_stripped}}FF)
$color_group_text_inactive = rgba({{colors.on_surface.default.hex_stripped}}FF)
$color_group_text_locked_active = rgba({{colors.on_surface.default.hex_stripped}}FF)
$color_group_text_locked_inactive = rgba({{colors.on_surface.default.hex_stripped}}FF)

$color_groupbar_active = rgba({{colors.primary.default.hex_stripped}}66)
$color_groupbar_inactive = rgba({{colors.outline_variant.default.hex_stripped}}66)
$color_groupbar_locked_active = rgba({{colors.error.default.hex_stripped}}66)
$color_groupbar_locked_inactive = rgba({{colors.error_container.default.hex_stripped}}66)

$color_splash = rgba({{colors.on_surface.default.hex_stripped}}FF)
$color_background = rgba({{colors.background.default.hex_stripped}}FF)
$color_shadow = rgba({{colors.shadow.default.hex_stripped}}EE)
$color_shadow_inactive = rgba({{colors.shadow.default.hex_stripped}}EE)

$color_pin_border_active = rgba({{colors.primary.default.hex_stripped}}AA)
$color_pin_border_inactive = rgba({{colors.primary.default.hex_stripped}}77)
